security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                success_handler: App\Security\LoginSuccessHandler
            custom_authenticators:
                - App\Security\GoogleAuthenticator 
            logout:
                path: app_logout
                target: front_home

    access_control:
        # Routes publiques
        - { path: ^/api/face-login, roles: PUBLIC_ACCESS }
        - { path: ^/api/face-compare, roles: PUBLIC_ACCESS }
        - { path: ^/face-authenticate, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }        # ← AJOUTER
        - { path: ^/connect/google/check, roles: PUBLIC_ACCESS }
        - { path: ^/api/validate-email, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        
        # Routes admin
        - { path: ^/admin, roles: ROLE_ADMIN }
        
        # Routes responsable
        - { path: ^/responsable, roles: ROLE_RESPONSABLE_CLUB }
        
        # Routes membre
        - { path: ^/membre, roles: ROLE_MEMBRE }
        
        # Routes utilisateur connecté
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/publication, roles: ROLE_USER }
        - { path: ^/forum, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_RESPONSABLE_CLUB, ROLE_MEMBRE, ROLE_ETUDIANT, ROLE_USER]
        ROLE_RESPONSABLE_CLUB: [ROLE_MEMBRE, ROLE_USER]
        ROLE_MEMBRE: [ROLE_USER]
        ROLE_ETUDIANT: [ROLE_USER]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10